### ISSUE TITLE
Unable to load assembly

### ISSUE THREAD

**Issue by GadgetGeekUK** [peteroupc/CBOR#10]
All loaded through nuget, v3.0.0. All files present, but I get:

> System.IO.FileLoadException occurred
>   HResult=0x80131045
>   Message=Could not load file or assembly 'CBOR, Version=3.0.0.0, Culture=neutral, PublicKeyToken=9cd62db60ea5554c' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

Noticed that this only occurs when running tests with ReSharper.

**Comment by GadgetGeekUK** [comment]
If I switch to V2.5.2, I get:

> System.IO.FileLoadException : Could not load file or assembly 'Numbers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9cd62db60ea5554c' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by peteroupc** [comment]
This issue is probably because the assembly was inadvertently delay-signed only, not strong-named.
This may be an [issue with MSBuild](https://github.com/Microsoft/msbuild/issues/2503).

**Comment by peteroupc** [comment]
Version 3.0.2 now resolves this issue with a workaround.
