### ISSUE TITLE
Encode options not honored for some nested objects

### ISSUE THREAD

**Issue by anands82** [peteroupc/CBOR#11]
A string longer than 4096 bytes is encoded as string stream even when option CBOREncodeOptions.NoIndefLengthStrings is specified, if the string is one among values of a map object. I suspect this is because options are dropped when encoding nested objects.

https://github.com/peteroupc/CBOR/blob/master/CBOR/PeterO/Cbor/CBORObject.cs#L3712

**Comment by peteroupc** [comment]
The bug in question was addressed.  Try it now.

**Comment by anands82** [comment]
I can confirm that the issue have been fixed. Could you please let me know when will the fix be released to nuget.

**Comment by peteroupc** [comment]
Version 3.0.3 is now released.
