### ISSUE TITLE
Decode back to any arbitrary object from CBOR object

### ISSUE THREAD

**Issue by zealizhe** [peteroupc/CBOR#12]
It is supported to encode any arbitrary object to CBORObject: CBORObject FromObject(object obj). Thank you! Any plan to support decode from CBORObject back to the original arbitrary object?

**Comment by peteroupc** [comment]
There are several issues that should be resolved before I implement a converter from CBOR objects to POD classes.

- What data types (source and destination) should the converter support?
- What source-type-to-destination-type conversions should the converter support?
-  How should the converter behave if data is of the wrong type (e.g., when the source is a string but the destination is a string) or if data is a number that's unsupported for the destination type (e.g., how should the converter behave if the source is say 67.59, but the destination stores only integers?  should the converter round to the nearest number, truncate fractions, raise an exception, something else?)

Also, newly added options for property name conversion have created a conflict between the Java and .NET versions of this library, but this is not a priority at the moment.

**Comment by peteroupc** [comment]
I have now added an initial implementation of `ToObject<T>()`.  However, this is only rough at the moment and my issues in the previous comment still stand.

**Comment by peteroupc** [comment]
Version 3.4.0 alpha, a prerelease, now includes a `ToObject()` method.  Please note what [the documentation](https://peteroupc.github.io/CBOR/docs/PeterO.Cbor.CBORObject.html) says about the "ToObject" method, especially the remark.

**Comment by peteroupc** [comment]
Version 3.4.0 beta contains an updated `ToObject()` method.
