### ISSUE TITLE
How to tag the ByteString inside an array

### ISSUE THREAD

**Issue by zealizhe** [peteroupc/CBOR#13]
I have an array of byteStrings, defined as follows:

var array = new List<byte[]>();
array.Add(byteString1);
array.Add(byteString2);
array.Add(byteString3);
var cborWithTag = CBORObject.FromObjectAndTagarray, 22);

The array was tagged 22 in cborWithTag. But each byteString in the array is not tagged properly, the value is still -1. 

I want to CBORObject.ToJSONString() to encode the byteString to base64. How can I achieve it?

**Comment by zealizhe** [comment]
According to RFC 7049 2.4.4.2, the tag should apply to all the byte strings except they are tagged differently.
   The data item tagged can be a byte string or any other data item.  In
   the latter case, the tag applies to all of the byte string data items
   contained in the data item, except for those contained in a nested
   data item tagged with an expected conversion.

**Comment by jimsch** [comment]
There is a difference between the phrase "the tag applies to" and "the tag is encoded on".  The first is a semantic statement the second is a syntactic statement.  I would only expect a single tag to be present in the encoding which appears to be what you are describing.

I would be surprised if the encoder did the byte to base64 encoding as this is a semantic statement.

**Comment by peteroupc** [comment]
@zealizhe: You are correct, tag 22 applies not only to byte strings, but also to "any other data item", such as arrays.  However, changing how `ToJSONString` encodes data to JSON might not be backward-compatible behavior without changing this project's major version.  But do you think this change is backward-compatible or can be backward-compatible? (Note that this project uses Semantic Versioning.)

**Comment by jimsch** [comment]
Perhaps just as important, since tags are not part of the JSON encoding unless you want to something very strange, how would you do the reverse operation on a parse?  They would say as strings rather than being converted to binary.  The fact that they were not symmetric would seem odd.

I am also not sure why you want to mix CBOR and JSON semantics.
