### ISSUE TITLE
Could not load file or assembly 'CBOR'

### ISSUE THREAD

**Issue by stefanstranger** [peteroupc/CBOR#22]
I've loaded the following libraries:

- PeterO.Numbers.1.0.2\lib\netstandard1.0\Numbers.dll'
- PeterO.Cbor.3.0.3\lib\netstandard1.0\CBOR.dll'

but I'm getting the following error:
Exception calling "GeneratePSK" with "2" argument(s): "Could not load file or assembly 'CBOR, Version=3.0.0.0, Culture=neutral, PublicKeyTok
en=9cd62db60ea5554c' or one of its dependencies. The system cannot find the file specified."

for this part of the following [code](https://github.com/tomidix/CSharpTradFriLibrary/blob/master/TradFriGui/Main.cs#L43)

Any ideas?
/Stefan

**Comment by peteroupc** [comment]
Try again with the latest version of the library, which is currently 3.4.0.
