### ISSUE TITLE
Null-handling behavior of certain As* methods of CBORObject

### ISSUE THREAD

**Issue by peteroupc** [peteroupc/CBOR#23]
CBORObject's `AsEInteger`, `AsEDecimal`, `AsEFloat`, `AsERational`, and `AsString` currently throw an exception when the CBOR object is `CBORObject.Null`.  Should these methods instead convert `CBORObject.Null` to `null`? (If so, why?)  

I don't mind if the answer is no, since I can then document the null-check idiom&mdash;

- `cbor.IsNull ? null : cbor.AsEInteger()`, or
- `(cbor==null || cbor.IsNull) ? null : cbor.AsEInteger()`,

for `AsEInteger` and likewise for the other four methods.  Is there a better null-check idiom here?

**Comment by jimsch** [comment]
My preference would be no.  However, it might be reasonable to provide a second set of functions mimicking the int? behavior perhaps AsEIntegerN

**Comment by peteroupc** [comment]
There are many ways an application could handle non-numbers (for `AsEDecimal`, etc.) or non-strings (for `AsString`), not just the current behavior of `AsEDecimal`, etc.  For example, in the case of AsEDecimal, an application could, among other things&mdash;

- replace non-finite numbers or `CBORObject.Null` with `CBORObject.Zero`,
- replace non-finite numbers or `CBORObject.Null` with `CBORObject.Null`,
- replace infinity or NaN with `CBORObject.Zero`, and non-numbers with `CBORObject.Null`,
- replace infinity or NaN with `CBORObject.Zero`, and throw an exception on non-numbers, or
- replace `CBORObject.Null` with null.

A proliferation of `AsEDecimal*`, etc. methods, implementing different behaviors, is undesirable.  I would rather have a reasonable default that works for most applications in most cases.  The current behavior of `AsEDecimal`, etc., may be that reasonable default.

**Comment by peteroupc** [comment]
Mentioned an alternate null-checking implementation in the docs.  This is enough for me, so closing this issue.
