### ISSUE TITLE
NuGet updates lead to StyleCop warnings

### ISSUE THREAD

**Issue by jgmdavies** [peteroupc/CBOR#26]
If I update PeterO.Cbor from 3.5.0 to 3.5.1 and PeterO.Numbers from 1.4.1 to 1.4.2, as suggested by NuGet in VS2019, I immediately get a large number of unwanted StyleCop warnings - I don't see why yet - anyone else?
Jim

**Comment by peteroupc** [comment]
I have migrated this project and the Numbers project to StyleCop Analyzers.

**Comment by jgmdavies** [comment]
Thanks for the quick response Peter.
Unfortunately it's severely affecting our build times as there are thousands of StyleCop warnings, e.g. tab/space and line break style differences which don't worry us, so for now I've gone back to the penultimate versions!
Best,
Jim

**Comment by peteroupc** [comment]
Released new versions that hopefully address this issue.

**Comment by jgmdavies** [comment]
That did the job, at least for me!

Many thanks Peter.
