### ISSUE TITLE
DateTimeKind.Utc

### ISSUE THREAD

**Issue by slipdef** [peteroupc/CBOR#27]
CBOR decodes any DateTime with Kind set to UTC. I would suggest to use Unspecified instead.

**Comment by peteroupc** [comment]
Be more specific.  Do you think this is an error in the library when it converts DateTimes to CBOR objects, or when it converts CBOR objects to DateTimes?  Note that the two CBOR tags are defined in terms of UTC, so it makes sense to convert objects with those tags to DateTimes with kind set to `Utc`.

**Comment by slipdef** [comment]
_Note that the two CBOR tags are defined in terms of UTC_ - sorry, I missed that CBOR transfers date as Unix timestamp, so it makes sense to set Kind to UTC when decoding.
