### ISSUE TITLE
Parser for CBOR Diagnostics

### ISSUE THREAD

**Issue by jimsch** [peteroupc/CBOR#29]
Feature Request:

Have you ever considered adding the reverse of the ToString function so that one could parse CBOR diagnositic text back into CBOR binary?  This is a much easier form to edit for files and I often use it for that.  I have written a fast and dirty version for myself, but it would be nice if there was one in the package.

**Comment by peteroupc** [comment]
Both RFC 7049 and its draft revision say that the CBOR diagnostic notation "is not meant to be parsed".  Therefore, the notation is not defined as rigorously as, say, JSON is.  Note also that the format of `CBORObject.ToString` "is intended to be human-readable, not machine-readable, the format is not intended to be parsed, and the format may change at any time", according to the documentation. Thus, that format might not exactly match the CBOR diagnostic notation at any given time.

For these reasons, I will decide against adding a diagnostic notation parser to the CBOR library.
