### ISSUE TITLE
Comparison and equality operators for CBORObject and CBORNumber

### ISSUE THREAD

**Issue by peteroupc** [peteroupc/CBOR#33]
In version 4.0, `PeterO.Cbor.CBORObject` will implement a total ordering in its `CompareTo` method (unlike before when two numbers of different kinds may still compare as equal).  

- CBORObject will also implement the "<", "<=", ">=", and ">" operators that call into CompareTo.
- But should CBORObject also implement the "==" and "!=" operators to call Equals, as FXCop rule [CA1036](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1036-override-methods-on-comparable-types.md) suggests?
    - Advantages: Consistent with other four operators, and notion of equality becomes consistent with Equals and CompareTo.
    - Disadvantages: Heavyweight, since CBOR objects can have arbitrary size.  These two operators do a reference equality by default, which is much faster, and changing them to do a value equality can cause performance issues for users that relied on the reference equality behavior of these operators and will make the .NET version of this library inconsistent with the Java version.

In version 4.0, the new `PeterO.Cbor.CBORNumber` will also have a `CompareTo` method, but will not do a total ordering, but a numerical comparison (meaning that two objects with different contents are equal if they express the same number).

- CBORNumber will also implement the "<", "<=", ">=", and ">" operators.
- But how should CBORNumber implement those operators &mdash; as a numerical comparison or as a total ordering?
- And should CBORNumber implement the "==" and "!=" operators, and if so, how?

See also:

MicrosoftDocs/visualstudio-docs#3728

**Comment by jimsch** [comment]
For myself, I have gotten into the habit of always assuming that '==' only refers to references and never to values.  If I know something is not a primitive, then I assume that I need to use Equals.  Keeping it that way makes life easier for things like insertion into lists where the contents may be equal, but I still want to get two copies.

**Comment by peteroupc** [comment]
Decided not to implement "==" and "!=".
