### ISSUE TITLE
Use FormatterServices.GetUninitializedObject as a fallback to using the Activator to create a new object

### ISSUE THREAD

**Issue by NickAcPT** [peteroupc/CBOR#34]
My suggestion is to use [`FormatterServices.GetUninitializedObject`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatterservices.getuninitializedobject) when it's not possible to invoke a constructor with `Activator.CreateInstance` in https://github.com/peteroupc/CBOR/blob/master/CBOR/PeterO/Cbor/PropertyMap.cs#L877

If it's not possible to use a constructor, using the `GetUninitializedObject` will allow CBOR to make a new object without trouble.

**Comment by peteroupc** [comment]
Have you encountered a real situation where deserialization fails in the way you describe?

**Comment by NickAcPT** [comment]
Sometimes it fails for classes that don't provide an empty constructor.

If you see that this suggestion is not helpful, feel free to close it.
