### ISSUE TITLE
Change in ToString from 3.x to 4.0

### ISSUE THREAD

**Issue by jimsch** [peteroupc/CBOR#36]
string x = CBORObject.True.ToString();

results in "21" not in "true"

I just upgraded due to the security issue and am having this problem when doing comparisons on strings produced.  The output of "{1:21}" is really not the same as "{1:true}"

**Comment by jimsch** [comment]
I am not doing the comparison in my program, but rather in the output.  I don't have any problems with doing updates of that string over time as things change, but this is not going to promote uses to understand things.  This string is dumped as part of examples for people in the COSE test suite.  Reading this is easier than reading a hex string.

**Comment by peteroupc** [comment]
Released version 4.1 which dealt with this issue.

**Comment by peteroupc** [comment]
Released version 4.0.1 which dealt with this issue.  However, note that for now, a more stable solution is to write your own method that converts CBOR objects to strings.  You can use the current implementation given in `CBORObject.ToString()` as a guide.
