### ISSUE TITLE
Missing attribute to change name of the properties

### ISSUE THREAD

**Issue by ondrejtomcik** [peteroupc/CBOR#43]
Greetings,
I would like to ask if there is plan, or already a solution (which I unfortunately didn't find) to introduce attribute which allow change of the source property name.
Same thing you have for example in JSON.Net - https://www.newtonsoft.com/json/help/html/JsonPropertyName.htm

The example how we currently work with the library is:
`CBORObject.DecodeFromBytes(data).ToObject(typeof(T), new PODOptions(false, true));`

Thanks

**Comment by peteroupc** [comment]
Declining.  In general, plain-old-data types that should be serialized with CBORObject should be those within the application's control.  As such, the application should already have full control of what names each of its properties should have.
