### ISSUE TITLE
AsString throws System.InvalidOperationException: Not a text string type

### ISSUE THREAD

**Issue by FateOri** [peteroupc/CBOR#52]
https://github.com/peteroupc/CBOR/blob/master/docs/PeterO.Cbor.CBORObject.md#AsString

Kind of unexpected. What's wrong with null here?

**Comment by peteroupc** [comment]
Indeed, `AsString` succeeds only if the CBOR object is a text string type (and not if the object encodes `null`, any other simple value, or any other major type).  The documentation already shows how to check for null values.  Can you explain your use case more; does it involve CBOR objects that can validly take either `CBORObject.Null` or a text string?

**Comment by FateOri** [comment]
I'm aware how to check for null values)))
instead of use default AsString method I need to use custom extension AsStringWithNullSupport()

use case:
fields have null values by default
they are optional
user may fill them or leave it 

to restore values of the object AsString method is used

what I think that if 

```cs
string nullStr = null;
var cbor = CBORObject.FromObject(nullStr);
```

doesn't throw exception then why would reverse operation

```cs
string nullStrBack = cbor.AsString();
```

can't work?

**Comment by peteroupc** [comment]
`AsString` is not exactly the "reverse" of `FromObject`; rather `ToObject` generally is.  Try `cbor.ToObject<String>()` rather than `AsString()`.

**Comment by FateOri** [comment]
nice))
