### ISSUE TITLE
Premature end of data

### ISSUE THREAD

**Issue by Lashar2** [peteroupc/CBOR#58]
The application uses serialized (Cbor) and compressed (DeflateStream) files that are read like:

    using (var stream = File.OpenRead(path))
    {
        using (var deflateStream = new DeflateStream(stream, CompressionMode.Decompress, true))
            return Deserialize(1, deflateStream);
    }

in .net 4 everything is fine, but after the migration to dotnet 6 an error began "Premature end of data" to appear

This place throws the error 

class CBORReader

    public CBORObject ReadForFirstByte(int firstbyte) {
	...
      // Read fixed-length data
      byte[] data = null;
      if (expectedLength != 0) {
        data = new byte[expectedLength];
        // include the first byte because GetFixedLengthObject
        // will assume it exists for some head bytes
        data[0] = unchecked((byte)firstbyte);
        if (expectedLength > 1 &&
          this.stream.Read(data, 1, expectedLength - 1) != expectedLength
          - 1) {
          throw new CBORException("Premature end of data");
        }
        ...
      }

I don’t know what has changed in the implementation of DeflateStream, but `this.stream.Read(data, 1, expectedLength - 1)` at some point 1 byte is read instead of 2, and code does not expect this

That's if this place is rewritten like:

    // include the first byte because GetFixedLengthObject
    // will assume it exists for some head bytes
    data[0] = unchecked((byte)firstbyte);
    if (expectedLength > 1)
    {
        var totalRead = 0;
        while (totalRead !=expectedLength-1)
        {
            var read = this.stream.Read(data, 1, expectedLength - totalRead - 1);
            if (read == 0)
                throw new CBORException("Premature end of data");
            totalRead += read;
        }

    }

this fix issue. 

`this.stream.Read` should be less optimistic

**Comment by peteroupc** [comment]
Resolved.
