### ISSUE TITLE
Props prefixed with "Is" are not decoded 

### ISSUE THREAD

**Issue by slipdef** [peteroupc/CBOR#59]
I translated this {"isFoo": true} to HEX here https://cbor.me/. It gave me this A1656973466F6FF5
Then I tried to decode it

```
public class Test
{
    public bool IsFoo { get; set; }
}

var test = CBORObject.DecodeFromBytes(Convert.FromHexString("A1656973466F6FF5")).ToObject<Test>();
```

 And I got object with IsFoo false.

If I rename IsFoo to Foo all works well.

**Comment by peteroupc** [comment]
Given the CBOR object `{"isFoo": true}`, rename the property `public bool IsFoo { get; set; }` to `public bool IsIsFoo { get; set; }`.

**Comment by slipdef** [comment]
```
If "useCamelCase" is true :
In the .NET version, for each eligible property or field name, the word "Is" is removed from the name if the name starts with that word, then the name is converted to camel case, 
```

What is the reason behind it?

**Comment by peteroupc** [comment]
The intent was to mimic, to some extent, the behavior in the Java version of the library (which uses a better established convention involving `get`, `set`, and `is` methods; see [Corda, for example](https://github.com/chrischabot/docs-os/blob/c15dbc8a371c3c2d275ff087052fcf9abd3e99ed/source/serialization.md)).

But as I've just found out, neither `System.Text.Json` nor Json.NET appear to treat property names starting with "Is" specially, compared to other property names.   But my CBOR library does, hence the suggestion in my previous comment.
