### ISSUE TITLE
Example "custom strategy for converting objects" contains null in result object

### ISSUE THREAD

**Issue by flocko-motion** [peteroupc/CBOR#61]
I tried using the example from 
> "The following example illustrates a custom strategy for converting objects of a given class into CBOR objects."

At the end of the program..
```
// Deserialize CBOR object
       cp2=cbor.ToObject<CPOD3>();
```
..cp2 is an object of type CPOD3 with all properties (Aa, Bb, Cc) being _null_

To run the example i wrapped the main code in a Main class and left everything else as it was (except: I had to remove the `private` attribute from class `CPOD3Converter`, because my compiler complained about private classes in a namespace)

Am I doing something really wrong or is the example broken? (I'm a JAVA developer learning C#, so please forgive me, if I'm missing something really obvious)

The full code is: 

```

using PeterO.Cbor;

public class CPOD3
{
    public string Aa { get; set; }
    public string Bb { get; set; }
    public string Cc { get; set; }
}

class CPOD3Converter : ICBORToFromConverter<CPOD3>
{
    public CBORObject ToCBORObject(CPOD3 cpod)
    {
        return CBORObject.NewMap()
           .Add(0, cpod.Aa)
           .Add(1, cpod.Bb)
           .Add(2, cpod.Cc);
    }
    public CPOD3 FromCBORObject(CBORObject obj)
    {
        if (obj.Type != CBORType.Map)
        {
            throw new CBORException();
        }
        var ret = new CPOD3();
        ret.Aa = obj[0].AsString();
        ret.Bb = obj[1].AsString();
        ret.Cc = obj[2].AsString();
        return ret;
    }
}

public class MainClass
{
    public static void Main(string[] args)
    {
        var cp2 = new CPOD3();
        cp2.Aa = "AA";
        cp2.Bb = "BB";
        cp2.Cc = "CC";
        var tm = new CBORTypeMapper().AddConverter(
            typeof(CPOD3),
            new CPOD3Converter());
        // Serialize CBOR object
        var cbor = CBORObject.FromObject(cp2, tm);
        // Deserialize CBOR object
        cp2 = cbor.ToObject<CPOD3>();
        Console.WriteLine($"Aa:{cp2.Aa}, Bb:{cp2.Bb}, Cc:{cp2.Cc}");
    }
}

```

**Comment by peteroupc** [comment]
The example is indeed broken.  The type mapper `tm` must be passed to `ToObject` just as it is to `FromObject`.  I will correct the example.

**Comment by flocko-motion** [comment]
Great! Now it works.. Thanks so much - that was really fast :)
