### ISSUE TITLE
byte[] objects are not converted correctly in the ToJSONString (C#)

### ISSUE THREAD

**Issue by carloscal** [peteroupc/CBOR#7]
Just run the Example code of https://github.com/peteroupc/CBOR/,  the byte object "new byte[] { 0, 1, 2}" produces "AAEC" in the JSON string.

**Comment by peteroupc** [comment]
The `ToJSONString` method works as documented (see http://peteroupc.github.io/CBOR/docs/PeterO.Cbor.CBORObject.html , where it says "Byte strings [that is, byte arrays] are converted to Base64 URL by default." And "AAEC" is the Base64 representation of the given byte array.

**Comment by carloscal** [comment]
Yeah I took a look on the code and saw that this is the default behavior when the byte string does not have a tag. Is there any way to modify this default behavior, maybe adding the tag 23 or using some option in the  CBOREncodeOptions ?

**Comment by peteroupc** [comment]
What do you expect byte arrays to be converted to? Tag 23 results in a Base16, tag 22 results in traditional base64.  If you expect byte arrays to be converted to regular arrays, I'm afraid that's not supported at the moment.

**Comment by carloscal** [comment]
I want to convert them to Base16.

**Comment by peteroupc** [comment]
In that case, using tag 23 on byte strings is the way to go.

**Comment by carloscal** [comment]
Got it. Thanks. It took me a little while to find in the documentation API  how to add a tag to a CBOR object, I used the FromObjectAndTag static method. I would be nicer so you can add the tag as an optional parameter in the Add method of the CBORObject, or add some code example on how to add a Tag in github readme examples text.  Great project BTW.
