### ISSUE TITLE
Question: changed encoding of `0.0` between 4.5.2 and 4.5.3

### ISSUE THREAD

**Issue by charlesroddie** [peteroupc/CBOR#72]
Curious about a change in encoding of `0.0`:
```
BitConverter.ToString(co.EncodeToBytes(CBORObject.FromObject(0.0)))
```

This gives:

4.5.2: `FA-00-00-00-00`
4.5.3 and 5.0.0-alpha1: `F9-00-00`

Both serializations are interpreted as `0.0` in https://cbor.me/ and https://cbor.me/ chooses `F9-00-00` when serializing `0.0`.

The [release notes](https://github.com/peteroupc/CBOR/blob/master/History.md) for 4.5.3 don't suggest anything and it would be good to put serialization changes in there:

> Version 4.5.3
> More bug fixes, including a fix to a problem that can occur when reading from compressed or network streams

**Comment by peteroupc** [comment]
Indeed, the change you mentioned was intended to fix the issue reported in: https://github.com/peteroupc/CBOR-Java/issues/24

**Comment by peteroupc** [comment]
This was done.
