### ISSUE TITLE
Support standard `BigInteger` type

### ISSUE THREAD

**Issue by knutwannheden** [peteroupc/CBOR#76]
I was wondering whether it would make sense to support the standard `System.Numerics.BigInteger` type for very large (larger than 64bit) integer values, rather than having to use the library-specific `EInteger` type or whether there should at least be some conversion functions.

**Comment by peteroupc** [comment]
Do you mean an integer with more than 2^64 bits?  Do you have a use case involving storing integers with that many bits?

**Comment by knutwannheden** [comment]
I am parsing JSON documents with numbers larger than 2^64 (as JSON doesn't have any limits here) and I am using CBOR to serialize them. My in-memory representation for these large numbers is BigInteger. Does that make aense?

**Comment by knutwannheden** [comment]
Thanks! I will try to implement this in my application code then.
