### ISSUE TITLE
Assembly does not have a strong signature.

### ISSUE THREAD

**Issue by jimsch** [peteroupc/CBOR#8]
I would like to apply a strong signature to my assemblies, however since I am referencing the CBOR (and indirectly NUMBERS) projects and they are not strongly signed it will not work.

Please release a new version with a strong signature.

**Comment by peteroupc** [comment]
If I release a strongly signed assembly, will I need to include the strong name key in the repository?

**Comment by jimsch** [comment]
No you do not need to include the key itself in the repository - although you need to make sure that if you are doing CI that the release version that the CI is running on at that point is tagged as not doing the strong signing.  I am in the process of creating a DEBUG, RELEASE and SHIP as targets where the only difference between SHIP and RELEASE are the signing.

For some reason Msft appears to recommend checking in the strong key to the repository (https://msdn.microsoft.com/en-us/library/wd40t7ad%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) but it makes no sense to me.

**Comment by peteroupc** [comment]
I have released version 2.5, which is like version 2.4.2 but with a strong name.

**Comment by jimsch** [comment]
I am seeing a strong name on Numbers, but not on CBOR. 

I guess that strong names are really just a way of having a longer more unique name that can be bound to a package.  It allows you to say - I tested with this specific version - use it.

**Comment by peteroupc** [comment]
Version 2.5 was mistakenly released without a strong name.  Version 2.5.1, just released, should remedy this.

**Comment by jimsch** [comment]
Yes that fixes it.  Thanks.

**Comment by jimsch** [comment]
You are going to end up hating me - You should probably update the dependency in the nuspec file to the 0.4.0 version of numbers as well.

**Comment by peteroupc** [comment]
Released version 2.5.2.

**Comment by snalesso** [comment]
Can this be closed?
