### ISSUE TITLE
MostInnerTag not in the drop?

### ISSUE THREAD

**Issue by jimsch** [peteroupc/CBOR#9]
I was going to try and get rid of all of my BigInteger warnings so I tried to switch from InnermostTag to MostInnerTag as suggested by the copy of the source code that I have suggests.  However, it appears that this is not in the most recent drop of the binaries.

**Comment by peteroupc** [comment]
MostInnerTag will use EInteger, which I didn't expose in the 2.x series.  MostInnerTag will be in version 3.0.
